// Copyright (c) the go-ruby-grpc/grpc authors
//
// SPDX-License-Identifier: BSD-3-Clause

package grpc

import "testing"

// The golden strings below are the verbatim output of grpc_tools_ruby_protoc
// (grpc-tools 1.83) for the matching .proto; codegen_oracle_test.go re-derives
// them live from the binary when it is installed. Keeping them inline lets the
// generator's byte-fidelity be asserted in CI without the Ruby toolchain.

const goldenHelloworld = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: helloworld.proto for package 'helloworld'

require 'grpc'
require 'helloworld_pb'

module Helloworld
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'helloworld.Greeter'

      rpc :SayHello, ::Helloworld::HelloRequest, ::Helloworld::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
`

const goldenRouteGuide = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: route_guide.proto for package 'routeguide'

require 'grpc'
require 'route_guide_pb'

module Routeguide
  module RouteGuide
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'routeguide.RouteGuide'

      rpc :GetFeature, ::Routeguide::Point, ::Routeguide::Feature
      rpc :ListFeatures, ::Routeguide::Rectangle, stream(::Routeguide::Feature)
      rpc :RecordRoute, stream(::Routeguide::Point), ::Routeguide::RouteSummary
      rpc :RouteChat, stream(::Routeguide::RouteNote), stream(::Routeguide::RouteNote)
    end

    Stub = Service.rpc_stub_class
  end
end
`

const goldenMultiService = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: svc.proto for package 'grpc.testing.foo'

require 'grpc'
require 'svc_pb'

module Grpc
  module Testing
    module Foo
      module EchoService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'grpc.testing.foo.EchoService'

          rpc :Echo, ::Grpc::Testing::Foo::Req, ::Grpc::Testing::Foo::Resp
        end

        Stub = Service.rpc_stub_class
      end
      module Other
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'grpc.testing.foo.Other'

          rpc :Ping, ::Grpc::Testing::Foo::Req, ::Grpc::Testing::Foo::Resp
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
`

const goldenNoPackage = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: nopkg.proto for package ''

require 'grpc'
require 'nopkg_pb'

module Bare
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Bare'

    rpc :Do, ::A, ::A
  end

  Stub = Service.rpc_stub_class
end
`

const goldenNested = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: nested.proto for package 'a.b'

require 'grpc'
require 'nested_pb'

module A
  module B
    module S
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'a.b.S'

        rpc :M, ::A::B::Outer::Inner, ::A::B::Outer::Inner
      end

      Stub = Service.rpc_stub_class
    end
  end
end
`

const goldenUnderscore = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: und.proto for package 'foo_bar.v1beta1'

require 'grpc'
require 'und_pb'

module FooBar
  module V1beta1
    module MyService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'foo_bar.v1beta1.my_service'

        rpc :Do, ::FooBar::V1beta1::My_msg, ::FooBar::V1beta1::My_msg
      end

      Stub = Service.rpc_stub_class
    end
  end
end
`

const goldenEmptyService = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: empty.proto for package 'e'

require 'grpc'
require 'empty_pb'

module E
end
`

const goldenMixed = `# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mixed.proto for package 'm'

require 'grpc'
require 'mixed_pb'

module M
  module Full
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'm.Full'

      rpc :Do, ::M::R, ::M::R
    end

    Stub = Service.rpc_stub_class
  end
end
`

// codegenCases pairs a ServiceFile with the grpc_tools_ruby_protoc golden it must
// reproduce byte-for-byte.
var codegenCases = []struct {
	name string
	file ServiceFile
	want string
}{
	{"helloworld", ServiceFile{
		ProtoFile: "helloworld.proto", Package: "helloworld",
		Services: []ServiceGen{{Name: "Greeter", Methods: []MethodGen{
			{Name: "SayHello", InputType: "helloworld.HelloRequest", OutputType: "helloworld.HelloReply"},
		}}},
	}, goldenHelloworld},

	{"route_guide", ServiceFile{
		ProtoFile: "route_guide.proto", Package: "routeguide",
		Services: []ServiceGen{{Name: "RouteGuide", Methods: []MethodGen{
			{Name: "GetFeature", InputType: "routeguide.Point", OutputType: "routeguide.Feature"},
			{Name: "ListFeatures", InputType: "routeguide.Rectangle", OutputType: "routeguide.Feature", ServerStreaming: true},
			{Name: "RecordRoute", InputType: "routeguide.Point", OutputType: "routeguide.RouteSummary", ClientStreaming: true},
			{Name: "RouteChat", InputType: "routeguide.RouteNote", OutputType: "routeguide.RouteNote", ClientStreaming: true, ServerStreaming: true},
		}}},
	}, goldenRouteGuide},

	{"multi_service", ServiceFile{
		ProtoFile: "svc.proto", Package: "grpc.testing.foo",
		Services: []ServiceGen{
			{Name: "EchoService", Methods: []MethodGen{{Name: "Echo", InputType: "grpc.testing.foo.Req", OutputType: "grpc.testing.foo.Resp"}}},
			{Name: "Other", Methods: []MethodGen{{Name: "Ping", InputType: "grpc.testing.foo.Req", OutputType: "grpc.testing.foo.Resp"}}},
		},
	}, goldenMultiService},

	{"no_package", ServiceFile{
		ProtoFile: "nopkg.proto", Package: "",
		Services: []ServiceGen{{Name: "Bare", Methods: []MethodGen{{Name: "Do", InputType: "A", OutputType: "A"}}}},
	}, goldenNoPackage},

	{"nested_type", ServiceFile{
		ProtoFile: "nested.proto", Package: "a.b",
		Services: []ServiceGen{{Name: "S", Methods: []MethodGen{{Name: "M", InputType: "a.b.Outer.Inner", OutputType: "a.b.Outer.Inner"}}}},
	}, goldenNested},

	{"underscore_package", ServiceFile{
		ProtoFile: "und.proto", Package: "foo_bar.v1beta1",
		Services: []ServiceGen{{Name: "my_service", Methods: []MethodGen{
			{Name: "Do", InputType: "foo_bar.v1beta1.my_msg", OutputType: "foo_bar.v1beta1.my_msg"},
		}}},
	}, goldenUnderscore},

	{"empty_service", ServiceFile{
		ProtoFile: "empty.proto", Package: "e",
		Services: []ServiceGen{{Name: "Empty"}},
	}, goldenEmptyService},

	{"mixed", ServiceFile{
		ProtoFile: "mixed.proto", Package: "m",
		Services: []ServiceGen{
			{Name: "Empty"},
			{Name: "Full", Methods: []MethodGen{{Name: "Do", InputType: "m.R", OutputType: "m.R"}}},
		},
	}, goldenMixed},
}

func TestGenerateRubyServicesGolden(t *testing.T) {
	for _, tc := range codegenCases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := GenerateRubyServices(tc.file)
			if err != nil {
				t.Fatalf("GenerateRubyServices: %v", err)
			}
			if got != tc.want {
				t.Errorf("mismatch\n--- got ---\n%s\n--- want ---\n%s", got, tc.want)
			}
		})
	}
}

// TestGenerateRubyServicesLeadingDotType covers a fully-qualified type written
// with the leading dot a FileDescriptorProto uses (".helloworld.HelloRequest").
func TestGenerateRubyServicesLeadingDotType(t *testing.T) {
	got, err := GenerateRubyServices(ServiceFile{
		ProtoFile: "helloworld.proto", Package: "helloworld",
		Services: []ServiceGen{{Name: "Greeter", Methods: []MethodGen{
			{Name: "SayHello", InputType: ".helloworld.HelloRequest", OutputType: ".helloworld.HelloReply"},
		}}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if got != goldenHelloworld {
		t.Errorf("leading-dot type not normalized:\n%s", got)
	}
}

// TestGenerateRubyServicesErrors covers the validation branches.
func TestGenerateRubyServicesErrors(t *testing.T) {
	cases := []struct {
		name string
		file ServiceFile
	}{
		{"no_proto_file", ServiceFile{Package: "x", Services: []ServiceGen{{Name: "S", Methods: []MethodGen{{Name: "M", InputType: "x.A", OutputType: "x.A"}}}}}},
		{"unnamed_service", ServiceFile{ProtoFile: "x.proto", Services: []ServiceGen{{Name: "", Methods: []MethodGen{{Name: "M", InputType: "A", OutputType: "A"}}}}}},
		{"unnamed_rpc", ServiceFile{ProtoFile: "x.proto", Services: []ServiceGen{{Name: "S", Methods: []MethodGen{{Name: "", InputType: "A", OutputType: "A"}}}}}},
		{"missing_input", ServiceFile{ProtoFile: "x.proto", Services: []ServiceGen{{Name: "S", Methods: []MethodGen{{Name: "M", InputType: "", OutputType: "A"}}}}}},
		{"missing_output", ServiceFile{ProtoFile: "x.proto", Services: []ServiceGen{{Name: "S", Methods: []MethodGen{{Name: "M", InputType: "A", OutputType: ""}}}}}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := GenerateRubyServices(tc.file); err == nil {
				t.Fatal("expected an error, got nil")
			}
		})
	}
}

// TestRubyTypeCrossPackage covers the fallback path for a type from another
// package (or a package-less file): the last dotted segment is the message name
// and the rest is its module-cased package.
func TestRubyTypeCrossPackage(t *testing.T) {
	cases := map[string]struct {
		fqn, pkg, want string
	}{
		"foreign_wkt":     {"google.protobuf.Empty", "helloworld", "::Google::Protobuf::Empty"},
		"foreign_leading": {".google.protobuf.Timestamp", "helloworld", "::Google::Protobuf::Timestamp"},
		"bare_no_package": {"Thing", "", "::Thing"},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			if got := rubyType(tc.fqn, tc.pkg); got != tc.want {
				t.Errorf("rubyType(%q, %q) = %q, want %q", tc.fqn, tc.pkg, got, tc.want)
			}
		})
	}
}

// TestPascalModuleEmptySegment covers the empty-subword branch of pascalModule
// (a package written with a trailing/leading underscore).
func TestPascalModuleEmptySegment(t *testing.T) {
	if got := pascalModule("a_"); got != "A" {
		t.Errorf(`pascalModule("a_") = %q, want "A"`, got)
	}
	if got := capitalizeFirst(""); got != "" {
		t.Errorf("capitalizeFirst(empty) = %q", got)
	}
}
